### ISSUE TITLE
Prefix customisation

### ISSUE THREAD

**Issue by hmlendea** [Kesuaheli/KeepInventoryCostPlugin#1]
Can you make a config option for the prefix itself so that we can customise it?

It would greatly help in making this plugin's chat outputs fit together with those from other plugins and achieve server-wide consistency.

Thanks!

**Comment by Kesuaheli** [comment]
Im not 100% happy with it. But Ive uploaded a new beta to Hanger [here](https://hangar.papermc.io/Kesuaheli/KeepInventoryCost/versions/0.2-SNAPSHOT)

Read the [note in *"Known issues"*](https://hangar.papermc.io/Kesuaheli/KeepInventoryCost/versions/0.2-SNAPSHOT) when updating.

**Comment by hmlendea** [comment]
Something seems borken.
This is whay I get with a fresh install using the mentioned version with a cleanly-generated config:
![image](https://github.com/user-attachments/assets/d30a9f0a-a6e3-4ea7-89d2-90c1883ed896)
